name: Build for Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.20.6'
      - name: Run build
        run: |
          cd web
          yarn
          cd packages/vue2
          yarn build
