name: Build for React Native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-rn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        run: |
          cd react-native
          yarn
          yarn lint

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Build android apk
        run: |
          cd react-native
          yarn
          cd android
          ./gradlew assembleDebug

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build ios
        run: |
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
          xcode-select --print-path
          cd react-native
          yarn
          cd ios && pod install
          echo "start build ios app"
          set -o pipefail
          xcodebuild -workspace app.xcworkspace -scheme app -sdk iphoneos -configuration Release -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO clean archive | xcpretty
