name: Build for iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v3
      - name: Build ios
        run: |
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
          xcode-select --print-path
          cd ios
          xcodebuild -resolvePackageDependencies
          echo "start build ios app"
          xcodebuild -scheme "ModerneShopping" -sdk iphoneos -configuration Release -destination generic/platform=iOS clean archive | xcpretty
