name: Build for React Native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-rn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: |
          cd react-native
          yarn
          yarn lint

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Build android apk
        run: |
          cd react-native/android
          ./gradlew assembleDebug

  build-ios:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v3
      - name: Build ios
        run: |
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
          cd react-native/ios
          xcodebuild -resolvePackageDependencies
          echo "start build ios app"
          xcodebuild -workspace app.xcworkspace \
          -scheme "app" \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          clean archive | xcpretty